const data = {
  products: [
    {
      name: 'Nike Slim T-shirt',
      slug: 'nike-slim-t-shirt',
      category: 'T-Shirts',
      image: '/images/p1.jpeg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality t-shirts',
    },
    {
      name: 'Adidas Fit T-Shirts',
      slug: 'adidas-fit-t-shirts',
      category: 'T-Shirts',
      image: '/images/p2.jpeg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality T-Shirts',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpeg',
      price: 200,
      countInStock: 15,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pant',
      image: '/images/p4.jpeg',
      price: 65,
      countInStock: 20,
      brand: 'Adidas',
      rating: 2.0,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};

export default data;
